version: '3'

tasks:

  build:
    desc: 'Build the container'
    cmds:
      - |
        docker build -t ml4floods-cli:latest .
    silent: false

  run: 
    desc: 'Run the ml4floods CLI'
    cmds:
      - |
        hatch run ml4floods-cli \
          --input-item https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/items/S2B_MSIL2A_20241031T105109_R051_T31SBD_20241031T133016 \
          --water-threshold 0.7 \
          --brightness-threshold 3500
    silent: false

  run-cwl:
    desc: 'Run the ml4floods CWL workflow'
    cmds:
      - task: build
      - |
        cwltool cwl-workflow/app-ml4floods.cwl#ml4floods \
          --input-item https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a/items/S2A_10SFG_20230618_0_L2A \
          --water-threshold 0.7 \
          --brightness-threshold 3500

    silent: false